name: matching-engine-ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  docker-build:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          tags: partion-matching-engine:ci
